version: 2
updates:
- package-ecosystem: maven
  directory: /
  schedule:
    interval: monthly
  ignore:
  # Several tests expect an exact version:
  - dependency-name: org.codehaus.groovy:groovy-binary
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
